#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""USB CDC SD-card debug client v2 with ACK/CRC, resume, progress, get-all."""
import argparse
import binascii
import os
import re
import sys
import time
from pathlib import Path

try:
    import serial
    from serial.tools import list_ports
except ImportError:
    print("pyserial is required: pip install pyserial", )
    raise

# 闁冲厜鍋撻柍鍏夊亾 Protocol regex 闁冲厜鍋撻柍鍏夊亾闁冲厜鍋撻柍鍏夊亾闁冲厜鍋撻柍鍏夊亾闁冲厜鍋撻柍鍏夊亾闁冲厜鍋撻柍鍏夊亾闁冲厜鍋撻柍鍏夊亾闁冲厜鍋撻柍鍏夊亾闁冲厜鍋撻柍鍏夊亾闁冲厜鍋撻柍鍏夊亾闁冲厜鍋撻柍鍏夊亾闁冲厜鍋撻柍鍏夊亾闁冲厜鍋撻柍鍏夊亾闁冲厜鍋撻柍鍏夊亾闁冲厜鍋撻柍鍏夊亾闁冲厜鍋撻柍鍏夊亾闁冲厜鍋撻柍鍏夊亾闁冲厜鍋撻柍鍏夊亾闁冲厜鍋撻柍鍏夊亾闁冲厜鍋撻柍鍏夊亾闁冲厜鍋撻柍鍏夊亾闁冲厜鍋撻柍鍏夊亾闁冲厜鍋撻柍鍏夊亾闁冲厜鍋撻柍鍏夊亾闁冲厜鍋撻柍鍏夊亾闁冲厜鍋撻柍鍏夊亾闁冲厜鍋撻柍鍏夊亾闁冲厜鍋撻柍鍏夊亾闁冲厜鍋撻柍鍏夊亾闁冲厜鍋撻柍鍏夊亾
GET_BEGIN_RE = re.compile(r"^\[GET_BEGIN\s+(\S+)\s+(\d+)(?:\s+(\d+))?\]$")
GET_END_RE   = re.compile(r"^\[GET_END\s+(\S+)\s+(\d+)\]$")
HEX_CRC_RE   = re.compile(r"^\[HEX\s+([0-9A-Fa-f]{8})\s+([0-9A-Fa-f]+)\s+([0-9A-Fa-f]{4})\]$")
OLD_HEX_RE   = re.compile(r"^([0-9A-Fa-f]{8})\s+([0-9A-Fa-f]+)$")
LS_FILE_RE   = re.compile(r"^FILE\s+(\d+)\s+(.+)$")
LS_DIR_RE    = re.compile(r"^DIR\s+(.+)$")

LOCK_FILE = os.path.join(os.environ.get("TEMP", os.path.expanduser("~")), "usb_sd_pull.lock")
PROGRESS_EVERY_LINES = 32
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM
# CRC-16/XMODEM

