#ifndef IMU_RECORD_MODE_H
#define IMU_RECORD_MODE_H

#define IMU_RECORD_MODE_POLLING 0
#define IMU_RECORD_MODE_INTERRUPT 1

#define IMU_RECORD_MODE IMU_RECORD_MODE_INTERRUPT

#endif /* IMU_RECORD_MODE_H */
