#ifndef RECORD_FEATURE_FLAGS_H
#define RECORD_FEATURE_FLAGS_H

#define RECORD_ENABLE_LVGL 1
#define RECORD_ENABLE_PPG 1
#define RECORD_ENABLE_ICM 1
#define RECORD_DEFAULT_RECORD_MS 30000U
#define RECORD_ISOLATE_AUX_TASKS 1
#define RECORD_USE_I2C3_MUTEX 1
#define RECORD_ICM_INIT_RETRY_COUNT 3U
#define RECORD_PPG_INIT_RETRY_COUNT 3U
#define RECORD_PPG_SAMPLE_RATE_HZ 50U
#define RECORD_PPG_FIFO_DRAIN_TIMEOUT_MS 100U
#define RECORD_PPG_FIFO_DRAIN_MAX_SAMPLES 8U
#define RECORD_PPG_INT_DRAIN_ROUNDS 4U
#define RECORD_PPG_I2C_TIMEOUT_MS 25U
#define RECORD_FAIL_FAST_ON_MODALITY_ERROR 1
#define RECORD_AUDIO_REOPEN_SAME_SEQ_ALLOWED 0
#define RECORD_AUDIO_ERROR_REQUESTS_STOP 1
#define RECORD_REQUIRE_PPG_FOR_FOUR_MODAL 1
#define RECORD_REQUIRE_ICM_FOR_FOUR_MODAL 1
#define RECORD_FAIL_STREAK_RESETS_WHEN_IDLE 1
#define RECORD_FAILED_MODALITY_REINITS_NEXT_START 1
#define RECORD_PPG_FAIL_STREAK_LIMIT 3U
#define RECORD_IMU_FAIL_STREAK_LIMIT 2U

#endif /* RECORD_FEATURE_FLAGS_H */
