#ifndef SESSION_SUMMARY_FIELDS_H
#define SESSION_SUMMARY_FIELDS_H

#define SESSION_SUMMARY_HAS_ECG 1
#define SESSION_SUMMARY_HAS_PPG 1
#define SESSION_SUMMARY_HAS_IMU 1
#define SESSION_SUMMARY_HAS_MIC 1

#define SESSION_SUMMARY_PPG_SAMPLES_KEY "ppg_samples"
#define SESSION_SUMMARY_PPG_WRITE_OK_KEY "ppg_write_ok"
#define SESSION_SUMMARY_PPG_WRITE_FAIL_KEY "ppg_write_fail"
#define SESSION_SUMMARY_PPG_DROP_BLK_KEY "ppg_block_drop"

#endif /* SESSION_SUMMARY_FIELDS_H */
