#ifndef APP_LVGL_ACCEPTANCE_UI_H
#define APP_LVGL_ACCEPTANCE_UI_H

#define APP_LVGL_ACCEPTANCE_UI 1
#define APP_LVGL_STOP_ON_PRESS 1
#define APP_LVGL_TOUCH_IRQ_FORCES_READ 1

#define APP_LVGL_TITLE_TEXT  "4-MODE REC"
#define APP_LVGL_START_TEXT  "START"
#define APP_LVGL_STOP_TEXT   "STOP"
#define APP_LVGL_SAVING_TEXT "SAVING"
#define APP_LVGL_READY_TEXT  "READY"

#endif /* APP_LVGL_ACCEPTANCE_UI_H */
